# Generated by Django 3.0 on 2023-09-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=800)),
                ('poster', models.CharField(max_length=500)),
                ('certificate', models.CharField(max_length=100)),
                ('cast_and_crew', models.CharField(max_length=300)),
                ('production_house_name', models.CharField(max_length=100)),
                ('producer_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('gentre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('screen_number', models.CharField(max_length=100)),
                ('audio_type', models.CharField(max_length=100)),
                ('audio_quality', models.CharField(max_length=800)),
                ('seat_charge', models.CharField(max_length=500)),
                ('total_set', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('from_time', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
                ('MOVIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Movie')),
                ('SCREEN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Screen')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=800)),
                ('ownername', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('established', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('is_premium', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('THEATRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Theatre')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Theate_promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('MOVIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Movie')),
                ('SHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shedule')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='THEATRE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Theatre'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=300)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reply', models.CharField(default='pending', max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seat', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('prebook', models.CharField(max_length=100)),
                ('SHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shedule')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
