# Generated by Django 4.2.5 on 2023-09-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
