# Generated by Django 4.2.5 on 2023-09-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_theate_promotion_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theate_promotion',
            name='MOVIE',
        ),
    ]
