# Generated by Django 4.2.5 on 2023-09-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_theate_promotion_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='theate_promotion',
            name='THEATRE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.theatre'),
            preserve_default=False,
        ),
    ]
