# Generated by Django 4.2.5 on 2023-09-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_theate_promotion_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_premium',
            new_name='type',
        ),
    ]
