# Generated by Django 4.2.5 on 2023-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_is_premium_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='password',
        ),
        migrations.AddField(
            model_name='theatre',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
