# Generated by Django 4.2.5 on 2023-10-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_movie_password_theatre_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOVIE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
            ],
        ),
    ]
