# Generated by Django 4.2.5 on 2023-10-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='voting',
            name='type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
