# Generated by Django 4.2.5 on 2023-10-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_voting_user_voting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='1', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('question', models.CharField(default='1', max_length=500)),
                ('answer', models.CharField(default='1', max_length=500)),
                ('MOVIE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
