
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('login/',views.login),
    path('login_post/',views.login_post),
    path('logout/',views.logout),
    path('admin_home/',views.admin_home),
    path('admin_change_password/', views.admin_change_password),
    path('admin_change_password_post/', views.admin_change_password_post),
    path('view_premium_users/', views.view_premium_users),
    path('view_premium_users_post/', views.view_premium_users_post),
    path('view_theatre_post/', views.view_theatre_post),
    path('view_theatre/', views.view_theatre),
    path('view_aproved_theatre/', views.view_aproved_theatre),
    path('view_aproved_theatre_post/', views.view_aproved_theatre_post),
    path('view_reject_theatre_post/', views.view_reject_theatre_post),
    path('view_reject_theatre/', views.view_reject_theatre),
    path('view_user/', views.view_user),
    path('view_user_post/', views.view_user_post),
    path('view_theatre_review/', views.view_theatre_review),
    path('view_review_post/', views.view_review_post),
    path('movie_review_post/', views.movie_review_post),
    path('movie_review/', views.movie_review),
    path('view_complaint/', views.view_complaint),
    path('view_complaint_post/', views.view_complaint_post),
    path('add_movie/', views.add_movie),
    path('add_movie_post/', views.add_movie_post),
    path('view_movies/', views.view_movies),
    path('view_movies_post/', views.view_movies_post),
    path('movies_delete/<id>', views.movies_delete),
    path('edit_movie/<id>', views.edit_movie),
    path('edit_movie_post/', views.edit_movie_post),
    path('complaint_reply_post/', views.complaint_reply_post),
    path('complaint_reply/<id>', views.complaint_reply),
    # path('aprove_premium/<id>', views.aprove_premium),



#     theatre
    path('theatre_home/',views.theatre_home),
    path('add_theatre_post/',views.add_theatre_post),
    path('add_theatre/',views.add_theatre),
    path('theatre_profile/',views.theatre_profile),
    path('aproving_theatre/<id>', views.aproving_theatre),
    path('reject_theatre/<id>', views.reject_theatre),
    path('edit_theatre/<id>', views.edit_theatre),
    path('edit_theatre_post/', views.edit_theatre_post),
    path('theatre_view_movies/', views.theatre_view_movies),
    path('theatre_view_movies_post/', views.theatre_view_movies_post),
    path('add_screen_post/', views.add_screen_post),
    path('add_screen/', views.add_screen),
    path('theatre_view_screen_post/', views.theatre_view_screen_post),
    path('theatre_view_screen/', views.theatre_view_screen),
    path('delete_screen/<id>', views.delete_screen),
    path('edit_screen/<id>', views.edit_screen),
    path('edit_screen_post/', views.edit_screen_post),
    path('add_time_shedule_post/', views.add_time_shedule_post),
    path('add_time_shedule/', views.add_time_shedule),
    path('view_shedule/', views.view_shedule),
    path('view_shedule_post/', views.view_shedule_post),
    path('delete_shedule/<id>', views.delete_shedule),
    path('edit_time_shedule/<id>', views.edit_time_shedule),
    path('edit_time_shedule_post/', views.edit_time_shedule_post),
    path('theatre_review_post/', views.theatre_review_post),
    path('theatre_review/', views.theatre_review),
    path('theatre_Movie_review/', views.theatre_Movie_review),
    path('theatre_Movie_review_post/', views.theatre_Movie_review_post),
    path('view_user_booking/', views.view_user_booking),
    path('view_user_booking_post/', views.view_user_booking_post),
    path('theatre_change_password_post/', views.theatre_change_password_post),
    path('theatre_change_password/', views.theatre_change_password),
    path('add_promotion/', views.add_promotion),
    path('add_promotion_post/', views.add_promotion_post),
    path('view_promotion/', views.view_promotion),
    path('view_promotion_post/', views.view_promotion_post),
    path('edit_promotion/<id>', views.edit_promotion),
    path('edit_promotion_post/', views.edit_promotion_post),
    path('delete_promotion/<id>', views.delete_promotion),





#     users

    path('login2/', views.login2),
    path('user_post/', views.user_post),
    path('user_profile/', views.user_profile),
    path('user_complaint_post/', views.user_complaint_post),
    path('user_view_complaints/', views.user_view_complaints),
    path('user_view_movie/', views.user_view_movie),
    path('user_view_promotion/', views.user_view_promotion),
    path('user_changepassword/', views.user_changepassword),
    path('user_view_theatre/', views.user_view_theatre),
    path('edit_userprofile/', views.edit_userprofile),
    path('view_movie_shedule/', views.view_movie_shedule),
    path('shedule_booking/', views.shedule_booking),
    path('user_movie_review/', views.user_movie_review),
    path('sent_theatre_review/', views.sent_theatre_review),
    path('user_view_movie_review/', views.user_view_movie_review),
    path('user_view_theate_review/', views.user_view_theate_review),
    path('sent_theatre_review1/', views.sent_theatre_review1),
    path('sent_theatre_review1/', views.sent_theatre_review1),
    path('sent_movie_review/', views.sent_movie_review),
    path('shedeule_booking/', views.shedeule_booking),
    path('view_booking_user/', views.view_booking_user),
    path('premium_shedeule_booking/', views.premium_shedeule_booking),
    path('view_prebook/', views.view_prebook),
    path('upvote/', views.upvote),
    path('downvote/', views.downvote),

    path('sent_question/', views.sent_question),
    path('user_view_movie_questions/', views.user_view_movie_questions),



]
